var numero =1
{
	var numero =2
	console.log(numero)


}//VARIAVEIS VAR NAO TEO ESCOPO GLOBAL OU SEJA SAO VISISEI TOTALMENTE, EXCETO EM FUNCOES QUE TEM SEU ESCOPO LOCAL
console.log(numero)

var num2 = 1
{
	let num2 = 2
	console.log(num2)

}//O LET TRABALHA COMO VARIAVEIS DE OUTRAS LINGUAGENS POIS ELE VE EM QUAL ESCOPO ESTAMOS
//MAS CASO NAO SEJA RESOLVIDO NO BLOCO ATUAL, ELE VAI SUBINDO ATE SE RESOLVER

console.log(num2)